name: Auth Handler

on:
  issues:
    types: [opened]

jobs:
  process-auth:
    if: contains(github.event.issue.labels.*.name, 'auth-request')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Process auth request
        env:
          CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
        run: |
          # 从 issue body 提取认证码
          CODE=$(echo "${{ github.event.issue.body }}" | grep -oP 'Code: \K[^\n]+')
          
          if [ -n "$CODE" ]; then
            # 获取访问令牌
            curl -s -X POST \
              -H "Accept: application/json" \
              -H "Content-Type: application/json" \
              --data "{\"client_id\":\"$CLIENT_ID\",\"client_secret\":\"$CLIENT_SECRET\",\"code\":\"$CODE\"}" \
              https://github.com/login/oauth/access_token > response.json
            
            # 添加评论
            if [ -f response.json ]; then
              TOKEN=$(jq -r .access_token response.json)
              if [ "$TOKEN" != "null" ]; then
                curl -X POST \
                  -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  -d "{\"body\":\"认证成功\"}" \
                  "${{ github.event.issue.comments_url }}"
              else
                curl -X POST \
                  -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  -d "{\"body\":\"认证失败: $(jq -r .error_description response.json)\"}" \
                  "${{ github.event.issue.comments_url }}"
              fi
            fi
          fi
          
          # 关闭 issue
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"state\":\"closed\"}" \
            "${{ github.event.issue.url }}"
