name: Auth Watcher

on:
  schedule:
    - cron: '*/1 * * * *'  # 每分钟运行一次
  workflow_dispatch:

jobs:
  check-auth-requests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Process auth requests
        env:
          CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
        run: |
          mkdir -p .auth
          
          # 检查是否有新的认证请求（通过URL参数）
          for code in $(find .auth -name "*.request" -type f 2>/dev/null); do
            echo "处理认证请求: $code"
            
            # 读取认证码
            auth_code=$(cat "$code")
            
            # 交换认证码获取token
            response=$(curl -s -X POST \
              -H "Accept: application/json" \
              -H "Content-Type: application/json" \
              --data "{\"client_id\":\"$CLIENT_ID\",\"client_secret\":\"$CLIENT_SECRET\",\"code\":\"$auth_code\"}" \
              https://github.com/login/oauth/access_token)
            
            # 保存token响应
            echo "$response" > "${code%.request}.json"
            
            # 删除请求文件
            rm "$code"
          done
      
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .auth/
          git commit -m "Process auth requests" || echo "No changes to commit"
          git push || echo "No changes to push"
