name: Auth Handler

on:
  repository_dispatch:
    types: [oauth-callback]

jobs:
  handle-oauth:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Exchange code for token
        env:
          CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          CODE: ${{ github.event.client_payload.code }}
        run: |
          mkdir -p .auth
          response=$(curl -s -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data "{\"client_id\":\"$CLIENT_ID\",\"client_secret\":\"$CLIENT_SECRET\",\"code\":\"$CODE\"}" \
            https://github.com/login/oauth/access_token)
          
          echo "$response" > ".auth/$CODE.json"
      
      - name: Commit token file
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .auth/
          git commit -m "Add auth token" || echo "No changes to commit"
          git push || echo "No changes to push"
