name: Generate Config

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-config:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate config file
        run: |
          echo "{" > config.json
          echo "  \"client_id\": \"${{ secrets.OAUTH_CLIENT_ID }}\"," >> config.json
          echo "  \"github_token\": \"${{ secrets.GITHUB_TOKEN }}\"" >> config.json
          echo "}" >> config.json
          
      - name: Commit config file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add config.json
          git commit -m "Update config" || echo "No changes to commit"
          git push || echo "No changes to push"
